#!/bin/bash

#
# Proxy Autodiscovery - HTTP
# ==========================
#
# This script autogenerates the http proxy config for dnf.

set -e
umask 0007


line="/etc/device/system/proxy/http"

if test -f "$line/disabled.bin"; then

  logger -t proxy-http-autodiscovery "proxy: disabling..."

  augtool --load-file=/etc/dnf/dnf.conf <<-EOF | /usr/bin/logger -t "{0}"
rm /files/etc/dnf/dnf.conf/main/#comment[following-sibling::*[1][self::proxy]]
rm /files/etc/dnf/dnf.conf/main/proxy
save
EOF

  logger -t proxy-http-autodiscovery "proxy: disabled."

  exit
fi

#
# Build http proxy options
# ------------------------

proxyname=""
port=""

if test ! -f "$line/name.txt"; then
  proxyname=""
else
  proxyname=$(head -n 1 "$line/name.txt")
fi

if test ! -f "$line/port.txt"; then
  port=3128
else
  port=$(head -n 1 "$line/port.txt")
fi


logger -t proxy-http-autodiscovery "proxy: http://${proxyname}:${port}"


#
# Configure dnf
# -------------
#
# Add the proxy option to dnf.

if test -n "${proxyname}"; then

  logger -t proxy-http-autodiscovery "proxy: enabling..."

  augtool --load-file=/etc/dnf/dnf.conf <<-EOF | /usr/bin/logger -t "{0}"
set /files/etc/dnf/dnf.conf/main/proxy http://${proxyname}:${port}
ins #comment before /files/etc/dnf/dnf.conf/main/proxy
set /files/etc/dnf/dnf.conf/main/#comment[following-sibling::*[1][self::proxy]] "device system proxy http set name=${proxyname} port=${port}"
save
EOF

  logger -t proxy-http-autodiscovery "proxy: enabled."

else

  logger -t proxy-http-autodiscovery "proxy: disabling..."

  augtool --load-file=/etc/dnf/dnf.conf <<-EOF | /usr/bin/logger -t "{0}"
rm /files/etc/dnf/dnf.conf/main/#comment[following-sibling::*[1][self::proxy]]
rm /files/etc/dnf/dnf.conf/main/proxy
save
EOF

  logger -t proxy-http-autodiscovery "proxy: disabled."

fi


